### ISSUE TITLE
Ability to add some additional parameters to the message text like gender.

### ISSUE THREAD

**Issue by CodeServant** [comahe-de/i18n4k#36]
In many language like Polish, Czech or Spanish, we distinguish between gender forms.
User in Spanish can be *usuario* (if male) or *usuaria* (if female), in Polish it is *użytkownik*, *użytkowniczka*.
For example if I want to print message for my user: "You got mail! from user Greta" this would look different in Polish depending on my users gender and Gretas gender. "You got" whould be translated to **Dostałaś** when female, or **Dostałeś**  when male. As i said before user would be **użytkowniczki** or **użytkownika** for female or male. So if both are females this message in polish should be "**Dostałaś** maila od **użytkowniczki** Grety". You can see that also Gretas name have different forms (it is [declension][declension] or polish [deklinacja][deklinacja]) and  depends on the situation in the sentence. If user sends mail to Greta, i want to print "You sent mail to Greta" now it is "*Wysłałaś* maila do  **Grety**" when *Wysłałaś* is female form of "you sent" and again you can see different form of Greta [declension][declension].
So the problem is how to prepare the translation document `MyMessages_en.properties` and `MyMessages_pl.properties`, so that i don't have to manage these forms in my code (because it should be as simple as `MyMessage.sayHello("word", gender = Gender.FEMALE)`). Managing these forms in code would be nightmare especially if you are not linguistic expert in all languages. Yet natives can translate these sentences and spot the pattern intuitively.  

I can see that this is complicated and I am not sure if I have clarified it. But form my perspective the solution whould be as follows.
Now programmers can create string like:
```youGotMail=You got mail from user {0}```
but if i whould like to customize it for the user in polish these should be like:
```youGotMail={0} maila od {1} {2}```
and manage this in code the 0 - male or female form of *you got*, 1 - *user* (male/female), 2 - *Greta* as specific [declension form][declension] (here polish [Dopełniacz][deklinacja]).  
So the translator should instead specify something like this:
```
youGotMail={youGot} maila od {user} {username.DOP}
youGotMail.youGot.FEMALE=dostałaś
youGotMail.youGot.MALE=dostałeś
youGotMail.user.FEMALE=użytkowniczki
youGotMail.user.MALE=użytkownika
```
The `username.DOP` then should have somewhere a dictionary (maby provided by translator) with all words that can be used by software, so that the programmer only specify the word, and then the correct form (here [dopełniacz][deklinacja]) is automaticaly applied.
The programmer whould then just provide required information about the word (IDE whould check required forms) like gender and specify the name (of Greta) and then i18n4k whould pick preferable form for the words.

The customizing of localed messages can be passed from programmes to the translators. Programmer should only specify some basic information about the word (passed as variable), like gender.
This greatly increases the user experience and i think it will become more widespread with [android 14][android].

I just think  this whould be fantastic feature, but maby I'm wrong and it's just overcomplicated and unnecesary.

[deklinacja]: https://pl.wikipedia.org/wiki/Deklinacja_w_j%C4%99zyku_polskim
[declension]: https://en.wikipedia.org/wiki/Declension
[android]: https://developer.android.com/about/versions/14/features/grammatical-inflection

**Comment by comahe-de** [comment]
Hi @CodeServant 

I can imagine the following message-format-pattern:

    {argument-number, select, value1 # text1 | value2 / value3 # text2 | ? otherwise-text}

Where the value of the argument at position "argument-number" is matched against "value1", "value2", "value3" or any other value. The corresponding text is then selected.

List of several values for the same text can be separated by slash "/"

Values and texts are trimmed (leading and tailing whitespaces are removed) and must not contain "," , "/", "\\" or "|". If these special characters are needed, they can be escaped via backslash "\\".

The texts themselves can also contain patterns. So, the patterns can be nested.

Example:

    "{0} has forgotten {1, select, female # her | ? his }  {3, select, one # bag | ? {2} bags}."

Usage:

    FORGOTTEN_BAG("Peter", "male", 1, "one") -> Peter has forgotten his bag.
    FORGOTTEN_BAG("Mary", "female", 2, "few") -> Mary has forgotten her 2 bags.

I can also image special selects for "gender" and "plural", where separate providers deliver the select value. 

Example:

    "{0} has forgotten {0, gender, female # her | ? his }  {1, plural, one # bag | ? {1} bags}."

Usage:

    FORGOTTEN_BAG("Peter",  1) -> Peter has forgotten his bag.
    FORGOTTEN_BAG("Mary", 2) -> Mary has forgotten her 2 bags.

HINT: I do not plan to manage directories to determine the gender of a word. This I will leaf up to you. You may provide a separate extension for i184k via pull request.

What do you think about it?

**Comment by CodeServant** [comment]
I was thinking about this for a while and I have some notes
## important numerals issue
There are many languages that don't rely on this simple car, cars, bag, bags rule. Examples are Czech, Polish, Ukrainian, Irish, Italian and more.
For example in polish you say 1 torba (bag), 2 torby (bags) but 5 toreb (bags). I found a great summary at [unicode.org][unicodeNums]
### my solutions
Change from `{argument-number, select, value1 # text1 | value2 / value3 # text2 | ? otherwise-text}` arguments like `value1` to regex instead of just compering text. And then programmer who doesn't have any idea about numerals in all those countries just passes the number and then framework applies specific rule.
The downside of this would be regex duplication for every line where the word occurs. So i would lobby on different solution.  

Making a special syntax for numerals seems good, and then make some kind of centralization for numeral rules, since it wont be changed for every sentence.

I can imagine that there would be 2 functions for numerals then. The one with number, where you don't provide, if it is plural or singular, and the one with just that (without number). You still have plural form without the risk of mising the right numeral form when definig quantity.
### possible future direction to consider
There can be a need in the future for changing numbers to words (like 100 to a hundred) or more plausable using [ordinal numerals][ordinalNumeral] (where genders are still there in some langs). Of course thats just my imagination so nothing to be bothered at this moment.

## gender forms
*I think that determining gender by persons name is not reliable, since there are names applied for both or dependant on the country, region, culture etc.*
I've done some reaserch and it seems that besides from regular [gender forms][gramGend] many languages have some form of **neuter**. Keeping genders forms in static context seems natural for me (because it is basically enum).  
I think the following categories would be necesery `FEMININE, MASCULINE, NEUTER, DOMINANT`. The `DOMINANT` would be created to secure case where f.e. in polish, you have male users (użytkownicy) and female users (użytkowniczki), then in polish DOMINANT=(użytkownicy+użytkowniczki)=użytkownicy, **which is the male form**. In polish you can even create soomething weard as _użytkowniszcza_ (users with no gender, that implies a bunch of "god knows what" that uses the program and is more a joke than regularity).  
So for polish FEMININE=użytkowniczki, MASCULINE=użytkownicy, NEUTER=użytkowniszcza, DOMINANT=MASCULINE.
DOMINANT can be treated as default when gender not specified or when you join male users with female  and get mixture of users (then DOMINANT is the form to use).
For languages with 2 gender forms probably NEUTER=DOMINANT.

## Declension
You can see hypothetical declension for english with [Wikipedia][hipDec].  
This is actually different type of parameter from the `select` one. The only one that is interested in this parameter shoud be translator (document creator). Programmer knews nothing about it. Programmer only passes (name, verb, adjective, ordinal numeral) a word f. e. name and then a proper declension form is provided by framework. So probably this would be interface, that when does not exists, just pass the word without changes. This interface would be implemented probably by programmer or some third party language providers, because it requires some kind of dictionary or databse.

In translation document (keeping your original idea) would be like this:
`{argument-number, declension, MIAN}` where `MIAN` is polish Nominative declension, defined in interface implementation.  The MIAN can be treated as function that transforms the word passed by programmer with the specific interface implementation.
Different [languages][decLang] can have different declensions.
Lets keep it complicated :) becouse required gender and if plural or not should be passed to the interface implementation to find proper declension.

Now you know your abc...

Of course my ideas are just starting point, but i've tried to make it as much generic as possible and simple to the programmer.

[unicodeNums]: https://www.unicode.org/cldr/charts/43/supplemental/language_plural_rules.html
[ordinalNumeral]: https://en.wikipedia.org/wiki/Ordinal_numeral
[gramGend]: https://en.wikipedia.org/wiki/Grammatical_gender
[hipDec]: https://en.wikipedia.org/wiki/Declension#English-speaking_perspective
[decLang]: https://en.wikipedia.org/wiki/Declension#Declension_in_specific_languages

**Comment by comahe-de** [comment]
Hi @CodeServant

Thank you for you many suggestion. 

## Regex

The idea with the regex is interesting, but as you said, the regex had to be repeated every times.  
It you be better for such special cases that an one [MessageValueFormatter](https://github.com/comahe-de/i18n4k/blob/master/i18n4k-core/src/commonMain/kotlin/de/comahe/i18n4k/messages/formatter/MessageValueFormatter.kt) created and added to 
(MessageFormatterDefault)[https://github.com/comahe-de/i18n4k/blob/master/i18n4k-core/src/commonMain/kotlin/de/comahe/i18n4k/messages/formatter/MessageFormatterDefault.kt] (with must be changed to be extendable).

## Plural

Thank you for the link. So it seems that there are only [6 cases](https://cldr.unicode.org/index/cldr-spec/plural-rules) that should cover all languages: zero, one (singular), two (dual), few (paucal), many, other. There are also some projects like [this](https://github.com/xyzsd/cldr-plural-rules) to read and evaluate the rules for [cardinals]( https://raw.githubusercontent.com/unicode-org/cldr-json/master/cldr-json/cldr-core/supplemental/plurals.json) and [ordinals](https://raw.githubusercontent.com/unicode-org/cldr-json/master/cldr-json/cldr-core/supplemental/ordinals.json).

So e.g. for Polish the following should work. 

    { 1, plural, one # miesiąc | few # miesiące | many # miesięcy | ? miesiąca }

Similar for ordinal.

## Gender forms

The example with the name was just for illustration. I know names are ambiguous.

I think the Gender-Provider for the locale should know the DOMINANT and return the appropriate grammatical gender based on the input. So I think DOMINANT is not needed in the translations files.

But the problem with genders seems also more complicated that only NEUTER, MASCULINE and FEMININE, as written in [your link](https://en.wikipedia.org/wiki/Grammatical_gender) or [here](https://en.wikipedia.org/wiki/List_of_languages_by_type_of_grammatical_genders). So beside a the tree predefined string contstanst for  NEUTER, MASCULINE and FEMININE, the Gender-Provider should be allowed to return any string for the special cases in the select-pattern.

## Declension

Yes that must be an interface that take the word and return the needed declension. At least in German (my mother tongue) the declension depends on the structure of the sentence. When this is also the case for other languages, something like this should be possible:

E.g. "I have read 5 pages of the book" would be in German "Ich habe 5 Seiten des Buches gelesen". Where the "Buch" is the normal translation for "book". But at this place in the sentence the genitive is needed and it becomes "Buches"

English

   "I have read 5 pages of the {0}"

German;

    "Ich habe 5 Seiten des {0 , declension, genitive} gelesen"


The Declension-Provider gets the word ("Buch") and the parameter string ("genitive") an can return the appropriate from. As you have written, this must be based on some dictionary. But as I'm not a language expert, the parameter string must be free text so that all special cases can be covered 

## ordinal numbers

The rules from CLDR mentions above could be used partly here. They say that there are zero, one (singular), two (dual), few (paucal), many, other. But not how the ordinal number is written. e.g. "1st" for English. 

So a provider per locate is needed.

Maybe also gender or declension is also needed. So probably a free text parameter string is needed again.

## written numbers

For low numbers it is common to write the word and not the numerals. So it would be could to have a provider per locale that can write the number in letters (ordinal and cardinal)

A parameter that determines which range of numbers should be written with letter instead of numerals would be needed

Maybe also gender or declension is also needed. So probably some additional  free text parameter string is needed again.

**Comment by CodeServant** [comment]
## Plural
The provided example works for Polish, but now programmer from code perspective would have to determine language and apply correct form for specific quantity.
`{ 1, plural, one # miesiąc | few # miesiące | many # miesięcy | ? miesiąca }`
When it comes to plural form in all languages there is simple division between plural and singular (like in english). You have book, books, książka, książki, libra, libros.  
Difference ocures only for specified quantities. For Polish 22 książki (22 books, *few*) but 22 books for Czech is (22 knih, *other*), so now its not *few* category, but *other*. In Czech 2 number is in *few* but 22 is in *other*, whereas in Polish 2 and 22 is in _few_. 
Managing this in code wouldn't be possible.  
That is why programmer should only specify quantity and framework determines correct form. But of course there should be secound construct to choose wheather you want plural without specifying quantity or singular, where this is as simple as in English or Deutsch. So if we don't want to provide quantity information for user programmer chooses between singular or plural and nothing else.  
The problem with plural or singular can be when we want to translate "I have some books". Here would be actually książek (*many* form), and _some_ is unspecified, but implies not many. To be honest I don't knew how to resolve this. Maby some third construct in translation document. If every language have one form for fuzzy quanities, this would be simpler (I checked Arabic and It seems to be true). In that case translator would just specify regular select and in code programmer manages this on their own (choosing f.e. when 2-7 _few_, 8-15 _some_, 16+ _many_).

## Gender forms
Actualy you can be right that some kind of gender detection is required.  
If i want to write "This book is small." in Polish book is actually FEMININE so this would be "Ta książka jest mała." where _Ta_ (this, FEMININE) and _mała_ (small, FEMININE). I belive there should be some king of gender inheritence where translation of small and this is dependant on the gender of the book. Something like
```
{1, genderDependant, 2, FEMININE # Ta |  MASCULINE # Ten | NEUTER # To} {2, declension, MIAN} jest {3, genderDependant, 2, FEMININE # mała |  MASCULINE # mały | NEUTER # małe}
```
The 3rd parameter in **genderDependant** is argument on which **genderDependant** depends on (here  `{2, declension, MIAN}`).
Programmer doesn't manage gender dependants. it is done by translator.
There could be also quantity dependant.

## ordinal numbers
When it comes to Polish you are right declension and gender is needed.

## written numbers
At least in Polish declension and gender are not needed here, but this should be investigated further.

**Comment by comahe-de** [comment]
@CodeServant 

## Plurals

As I unterstood, the [rules]( https://raw.githubusercontent.com/unicode-org/cldr-json/master/cldr-json/cldr-core/supplemental/plurals.json)  are pretty exhaustive:

Polish:
 
```json
      "pl": {
        "pluralRule-count-one": "i = 1 and v = 0 @integer 1",
        "pluralRule-count-few": "v = 0 and i % 10 = 2..4 and i % 100 != 12..14 @integer 2~4, 22~24, 32~34, 42~44, 52~54, 62, 102, 1002, …",
        "pluralRule-count-many": "v = 0 and i != 1 and i % 10 = 0..1 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 12..14 @integer 0, 5~19, 100, 1000, 10000, 100000, 1000000, …",
        "pluralRule-count-other": "   @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …"
      },
```

Czech:
```json
"cs": {
        "pluralRule-count-one": "i = 1 and v = 0 @integer 1",
        "pluralRule-count-few": "i = 2..4 and v = 0 @integer 2~4",
        "pluralRule-count-many": "v != 0   @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …",
        "pluralRule-count-other": " @integer 0, 5~19, 100, 1000, 10000, 100000, 1000000, …"
      },
```

I think this is what you have described.

Yes programmer would know nothing about it. He would just write `COUNT_OF_MONTHS(4)`

And the text from the translator would be:

English

    {0} {0, plural, one # month | ? months }
    => 4 months 

Polish

    {0} {0, plural, one # miesiąc | few # miesiące | many # miesięcy | ? miesiąca }
    => 4 miesiące



## Gender forms

You don't need this "genderDependant" you just reuse the same parameter (the one that determines the gender)

Code

    SMALL_THING("book")

English

    This {0} is small

Polish

    {0, gender,  FEMININE # Ta |  MASCULINE # Ten | NEUTER # To} {0, declension, MIAN} jest {0, gender, FEMININE # mała |  MASCULINE # mały | NEUTER # małe}

**Comment by CodeServant** [comment]
ok that seems legit

**Comment by comahe-de** [comment]
Spitted into #41, #42, #43, #44, #45, #46 and #47
